// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3BrPZrmc1kdrM9wAtZgcTj
// Component: CmVoENMZXh
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Avatar from "../../Avatar"; // plasmic-import: FQyAt-uxPU/component
import TextInput from "../../TextInput"; // plasmic-import: D_5NwTMa2Ey/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_plasmic_chat_app.module.css"; // plasmic-import: 3BrPZrmc1kdrM9wAtZgcTj/projectcss
import sty from "./PlasmicSidebar.module.css"; // plasmic-import: CmVoENMZXh/css

export const PlasmicSidebar__VariantProps = new Array();

export const PlasmicSidebar__ArgProps = new Array("username");

function PlasmicSidebar__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"headerProfile"}
        data-plasmic-override={overrides.headerProfile}
        hasGap={true}
        className={classNames(projectcss.all, sty.headerProfile)}
      >
        {true ? (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___5AsM1)}
          >
            <Avatar
              data-plasmic-name={"userAvatar"}
              data-plasmic-override={overrides.userAvatar}
              className={classNames("__wab_instance", sty.userAvatar)}
            />

            <div className={classNames(projectcss.all, sty.freeBox___7J0Z)}>
              {p.renderPlasmicSlot({
                defaultContents: "Enter some text",
                value: args.username
              })}
            </div>
          </p.Stack>
        ) : null}

        <p.PlasmicImg
          data-plasmic-name={"logoutIcon"}
          data-plasmic-override={overrides.logoutIcon}
          alt={""}
          className={classNames(sty.logoutIcon)}
          displayHeight={"16px"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"16px"}
          loading={"lazy"}
          src={{
            src: "/plasmic/plasmic_chat_app/images/logoutsvg.svg",
            fullWidth: 150,
            fullHeight: 150,
            aspectRatio: 1
          }}
        />
      </p.Stack>

      <div
        data-plasmic-name={"searchInputWrapper"}
        data-plasmic-override={overrides.searchInputWrapper}
        className={classNames(projectcss.all, sty.searchInputWrapper)}
      >
        <TextInput
          data-plasmic-name={"searchRoomTextInput"}
          data-plasmic-override={overrides.searchRoomTextInput}
          className={classNames("__wab_instance", sty.searchRoomTextInput)}
          placeholder={"Search room by name..."}
        />
      </div>

      <div
        data-plasmic-name={"addNewRoomWrapper"}
        data-plasmic-override={overrides.addNewRoomWrapper}
        className={classNames(projectcss.all, sty.addNewRoomWrapper)}
      >
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
        >
          {"Add New Room"}
        </div>
      </div>

      <div
        data-plasmic-name={"chatListWrapper"}
        data-plasmic-override={overrides.chatListWrapper}
        className={classNames(projectcss.all, sty.chatListWrapper)}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerProfile",
    "userAvatar",
    "logoutIcon",
    "searchInputWrapper",
    "searchRoomTextInput",
    "addNewRoomWrapper",
    "text",
    "chatListWrapper"
  ],

  headerProfile: ["headerProfile", "userAvatar", "logoutIcon"],
  userAvatar: ["userAvatar"],
  logoutIcon: ["logoutIcon"],
  searchInputWrapper: ["searchInputWrapper", "searchRoomTextInput"],
  searchRoomTextInput: ["searchRoomTextInput"],
  addNewRoomWrapper: ["addNewRoomWrapper", "text"],
  text: ["text"],
  chatListWrapper: ["chatListWrapper"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSidebar__ArgProps,
          internalVariantPropNames: PlasmicSidebar__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicSidebar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSidebar";
  } else {
    func.displayName = `PlasmicSidebar.${nodeName}`;
  }
  return func;
}

export const PlasmicSidebar = Object.assign(
  // Top-level PlasmicSidebar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerProfile: makeNodeComponent("headerProfile"),
    userAvatar: makeNodeComponent("userAvatar"),
    logoutIcon: makeNodeComponent("logoutIcon"),
    searchInputWrapper: makeNodeComponent("searchInputWrapper"),
    searchRoomTextInput: makeNodeComponent("searchRoomTextInput"),
    addNewRoomWrapper: makeNodeComponent("addNewRoomWrapper"),
    text: makeNodeComponent("text"),
    chatListWrapper: makeNodeComponent("chatListWrapper"),
    // Metadata about props expected for PlasmicSidebar
    internalVariantProps: PlasmicSidebar__VariantProps,
    internalArgProps: PlasmicSidebar__ArgProps
  }
);

export default PlasmicSidebar;
/* prettier-ignore-end */
