// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";
import { PlasmicSignup } from "../components/plasmic/plasmic_chat_app/PlasmicSignup";
import { useRouter } from "next/router";

function Signup() {
  return (
    <ph.PageParamsProvider
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicSignup />
    </ph.PageParamsProvider>
  );
}

export default Signup;
